services:
  mongodb:
    image: mongo:latest
    container_name: mongodb-projeto-forms
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./backend
    container_name: api-projeto-forms
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/portal_noticias
      - JWT_SECRET=sua_chave_secreta_aqui
      - PORT=3000
    volumes:
      - ./backend:/app
    command: npm run dev
    depends_on:
      - mongodb

  # NOVO: MÃ³dulo ASP.NET Core para destacar seu perfil na vaga
  audit-service:
    build: ./audit-service
    container_name: audit-projeto-forms
    ports:
      - "5000:5000"
    environment:
      - ConnectionStrings__MongoDb=mongodb://mongodb:27017
    depends_on:
      - mongodb

  frontend:
    build: ./frontend
    container_name: frontend-projeto-forms
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mongo-data: